### PR TITLE
COMP 530 Clean-up

### PR DESCRIPTION
**Pull request by donporter**
Hi gang,

I wanted to use this base image in COMP 530 this semester, and had difficulty rebuilding it.  I ended up significantly rewriting the dockerfile in the process of debugging, but tried to keep the result as similar as possible.

Specifically, I would advise against using moving tags like 'latest', which can change over time and render the build broken even if this code didn't change.  

Change 1: Newer versions of the vim auto complete plugin (YouCompleteMe) must be built as non-root.  This is a huge hassle for docker build, which runs as root by default.  Add a fake user, ramses, to do the build/install, then copy to root's .vim.  

Change 2: Explicate the Ubuntu version (then roll forward to 22.04).  Builds on 18.04, 20.04, and 22.04.  After the other changes, was a one-liner.  Rather than base on another, simpler repo.  Now the Dockerfile is only relative to a base Ubuntu image.

Change 3: Add emacs support and a .emacs file.  I am an emacs user.  Probably enough said.

Change 4: General streamlining.  There were multiple, often repetitive apt installs+cleans, needless use of sudo and scripts in general.  I think the single dockerfile is cleaner than adding and deleting scripts.  I hope the image build itself goes faster as well.

### CODE REVIEW

**Comment by eric-unc** [comment]
If Kris doesn't respond I am capable of merging this, but would prefer to wait since I'm not familiar enough with Docker to notice anything wrong with it, though perhaps KJ hasn't touched Docker himself in a while.

**Comment by donporter** [comment]
I added one more change: manpages + set the local for US English.

**Comment by donporter** [comment]
> If Kris doesn't respond I am capable of merging this, but would prefer to wait since I'm not familiar enough with Docker to notice anything wrong with it, though perhaps KJ hasn't touched Docker himself in a while.

That's fine.  Don't want to step on any toes.  I hope to get an update out by Monday's class.  Worst case I can direct students to a forked repo.

**Comment by eric-unc** [comment]
It's been two years since KJ taught 211 so he probably wouldn't be too offended, but updating whatever's on DockerHub is something I think only he can do.

Maybe should cc @brent-munsell on this, but he hasn't touched the base image at all while teaching, just used what worked.

**Comment by donporter** [comment]
Small follow-up: Review this at your leisure. I think the only thing that actually matters for Monday is pushing the built image to dockerhub, which I can do before this merges.

**Comment by brent-munsell** [comment]
Quick question, Since I'm using this repo for Comp 211, I'm not entirely sure how this may affect my students ... if any ... thoughts?

**Comment by eric-unc** [comment]
@brent-munsell Docker Hub relies on a specific commit so if this was merged it would not change things immediately. But then [this PR](https://github.com/comp211/learncli211/pull/1) would. I don't really think there should be separate images for 211 and 530, since these changes would be positive for 211 too.

**Comment by brent-munsell** [comment]
Ahhh ok, got it, I didn't realize that 530 was a separate repo (thought just update the 211 one).

After the semester ends, would love to get together with Don and the 530 team to see how we can make just one repo that can be used for 211, 530, etc.

Brent

**Comment by donporter** [comment]
I think this is a fair question.  This is being merged into the 211 repo.  But the current 211 course would only be affected by any of these changes if you rebuilt the docker image and posted it on dockerhub; the other 211 scripts pull the already-built one from dockerhub.

A few of the later commits on this branch are adding features that may be irrelevant to 211.  Probably harmless other than wasting space.  But I can see how one might want to add customizations per course.

Otherwise, the main change from a 211 perspective is (1) the ability to rebuild the 211 image from source - which does not currently work, and (2) the ability to more easily roll forward to newer ubuntu versions (and rolling forward to 22.04).

I don't mind paring this back if you have input, or going over this with you if you like.  I probably will add a few more packages for 530 before all is said and done.

**Review by KrisJordan — APPROVED** [review]
lgtm

**Pull request merged**
