### PR TITLE
Fix format-c alias (need quotes)

### PR DESCRIPTION
**Pull request by jesse-wei**
Fixes bug in bash alias, quotes required for wildcard ( `"*.c"`).

### CODE REVIEW

**Comment by eric-unc** [comment]
Can you check why CI is failing?

**Comment by eric-unc** [comment]
o 
image

**Review by eric-unc — APPROVED** [review]

**Comment by eric-unc** [comment]
Fuck it imma merge it anyway

**Comment by jesse-wei** [comment]
I'm really thinking the issue stems from CI and not the code, similar to #13 ("failed docker ci job is spurious"). Plus, this commit just adds some quotes in bash, and I built the image locally and tested.

If you go to this repo's commit history on GitHub, click any GH actions green check mark, and click details, you always get `{"error": "Our service is temporarily unavailable. We'll be back soon!"}`. For example, on the latest commit 7c52f86, I get sent [here](https://hub.docker.com/redirect/?resource_uri=/api/audit/v1/action/47428899-0e79-423f-8790-1090d28c2105/).

**Comment by eric-unc** [comment]
I can't technically merge until CI passes

**Comment by eric-unc** [comment]
@donporter Docker CI keeps going down and I don't have the ability to force merge this. Can you look into it? (sorry for all the email spam)

**Review by brent-munsell — APPROVED** [review]
test

**Review by KrisJordan — APPROVED** [review]
lgtm

**Comment by eric-unc** [comment]
Thanks!

**Comment by jesse-wei** [comment]
Thanks!

**Pull request merged**
